# Generated by Django 4.1.5 on 2023-11-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('dec', models.CharField(max_length=254)),
                ('image', models.CharField(max_length=500)),
                ('imageone', models.CharField(max_length=500)),
                ('imagetwo', models.CharField(max_length=500)),
                ('imagethree', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=150)),
                ('cato', models.CharField(max_length=150)),
                ('sale', models.BooleanField(default=False)),
                ('rating', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('featured', models.BooleanField(default=True)),
            ],
        ),
    ]
