# Generated by Django 4.1.5 on 2023-11-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('off', models.IntegerField()),
                ('vallidon', models.BooleanField(default=True)),
            ],
        ),
    ]
