# Generated by Django 4.1.5 on 2023-12-02 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbackend', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
