# Generated by Django 4.1.5 on 2023-12-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbackend', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
